%% Setting up parameters
clear; close all; clc;

u_x_star = load("matlab.mat");
u_x_star = u_x_star.u_x_star;
% max(u_x_star)
p.N = 1024;
p.Lx = 32*pi;
p.dx = p.Lx/p.N;
p.x = 0:p.dx:p.Lx -p.dx;
var.sensors = p.x(1:10:p.N);
var.nu=1;
p.mu=100;

%% Calculate c
h_hat = diff(var.sensors);
h_hat(32:1024) = h_hat(end);
f = sin(p.x);
h = max(h_hat);
F_temp = griddedInterpolant(p.x, f);
F = griddedInterpolant(var.sensors, F_temp(var.sensors));
f_int = F(p.x);
lhs = norm(f - f_int).^2;
rhs = h.^2 * norm(gradient(f)).^2;
var.c = lhs/rhs;
var.c
%% Calculate minimun N sensors
bracket = (-4/3 * (2/var.nu - p.mu + u_x_star)).^(3/4);
constants = var.nu^(1/4) / (p.mu*var.c^(1/4));

% h_hat = bracket * constants;


a = p.dx*p.N;
b = 1./(bracket * constants);
disp("Max number of sensors needed at least: " + max(a*b));

%% Calculate term in bracket given uniform placement
% h_hat = h_hat-0.574;
xx = [];
yy = [];
mu = 3.73;
disp("Number of sensors generated by h: " + sum(1./h_hat)*p.dx);
for mu =0:1:100

xx = [xx, mu];
rho = 3/4*(mu^4*var.c*h_hat.^4/var.nu).^(1/3);
final_bracket = 2/var.nu - mu + max(u_x_star )+ rho;   
disp("Maximum value in bracket: " + max(final_bracket))
yy= [yy, max(final_bracket)];
end

plot(xx, yy, "LineWidth",3)
xlabel("\mu", "Interpreter","tex")
ylabel("Max value in bracket")
fontsize(24, "points")