function vars = DataAssimilationVariables_KSE(p)
% Author: Collin Victor. Last modified on 2020-09-25.
% Adapted for use by NSE 2D DA programs
% Initializes information for various types of observer regimes
% Including: Movement types of observers (i.e. mobile and static), type of
% interpolation, time type of observers (i.e. Chi vs Delta), and observer reset
% functionality.
vars = repelem(struct,1,1);
i = 0;
num_sensors = 33;
K = 0;
% initialSensorLocations = p.x(sort(randperm(num_sensors)));
initialSensorLocations = linspace(p.x(1), p.x(end), num_sensors);
% Uncomment the type of observer you want to use.
%% Uniform grid setup
    % i = i+1;
    % vars(i).observer_type = "Uniform";
    % vars(i).interpolation_type = "linear";
    % vars(i).sensors = linspace(p.x(1), p.x(end), num_sensors);
    % vars(i).off_grid = true;
    % vars(i).error = NaN(1,p.num_timesteps);
    % vars(i).error_aot = vars(i).error;
    % vars(i).marker = 's';
    % vars(i).color = 'blue';
    % vars(i).im = [];
%% Lagrangian
    % i = i+1;
    % vars(i).observer_type = "Lagrangian";
    % vars(i).interpolation_type = "linear";
    % vars(i).sensors = initialSensorLocations;
    % vars(i).marker = 's';
    % vars(i).diameter = 0;
    % vars(i).rho = 0;
    % vars(i).color = [0.502, 0, 0.408];
    % vars(i).off_grid = true;
    % vars(i).error = NaN(1,p.num_timesteps);
    % vars(i).error_aot = vars(i).error;
    % vars(i).amplitude = 0;
    % vars(i).stokes_number = [];
    % vars(i).im = [];
%% Lagrangian-Creeps 40
    % i = i+1;
    % vars(i).observer_type = "Lagrangian";
    % vars(i).interpolation_type = "linear";
    % vars(i).sensors = initialSensorLocations;
    % vars(i).marker = 's';
    % vars(i).diameter = 0;
    % vars(i).rho = 0;
    % vars(i).color = 'yellow';
    % vars(i).off_grid = true;
    % vars(i).error = NaN(1,p.num_timesteps);
    % vars(i).error_aot = vars(i).error;
    % vars(i).amplitude = 40;
    % vars(i).stokes_number = [];
    % vars(i).im = [];
 %% Inertia sensors St=0.001
    % i = i+1;
    % vars(i).observer_type = "Inertia";
    % vars(i).interpolation_type = "linear";
    % vars(i).sensors = linspace(p.x(1), p.x(end), num_sensors);
    % vars(i).vel = zeros(1, num_sensors);
    % vars(i).rho = 0.0139197;
    % vars(i).diameter = 10;
    % vars(i).marker = 'o';
    % vars(i).color = "cyan";
    % vars(i).off_grid = true;
    % vars(i).error = NaN(1,p.num_timesteps);
    % vars(i).error_aot = vars(i).error;
    % vars(i).im = [];
    % vars(i).stokes_number = [];
 %% Inertia sensors St=0.01
    % i = i+1;
    % vars(i).observer_type = "Inertia";
    % vars(i).interpolation_type = "linear";
    % vars(i).sensors = linspace(p.x(1), p.x(end), num_sensors);
    % vars(i).vel = zeros(1, num_sensors);
    % vars(i).rho = 0.139197;
    % vars(i).diameter = 10;
    % vars(i).marker = 'o';
    % vars(i).color = "cyan";
    % vars(i).off_grid = true;
    % vars(i).error = NaN(1,p.num_timesteps);
    % vars(i).error_aot = vars(i).error;
    % vars(i).im = [];
    % vars(i).stokes_number = [];
 %% Inertia sensors St=0.1
    % i = i+1;
    % vars(i).observer_type = "Inertia";
    % vars(i).interpolation_type = "linear";
    % vars(i).sensors = linspace(p.x(1), p.x(end), num_sensors);
    % vars(i).vel = zeros(1, num_sensors);
    % vars(i).rho = 1.39197;
    % vars(i).diameter = 10;
    % vars(i).marker = 'o';
    % vars(i).color = "cyan";
    % vars(i).off_grid = true;
    % vars(i).error = NaN(1,p.num_timesteps);
    % vars(i).error_aot = vars(i).error;
    % vars(i).im = [];
    % vars(i).stokes_number = [];
%%  Inertia sensors St=1
    % i = i+1;
    % vars(i).observer_type = "Inertia";
    % vars(i).interpolation_type = "linear";
    % vars(i).sensors = initialSensorLocations;
    % vars(i).vel = zeros(1, num_sensors);
    % vars(i).rho = 13.9197;
    % vars(i).diameter = 10;
    % vars(i).marker = 'o';
    % vars(i).color = "magenta";
    % vars(i).off_grid = true;
    % vars(i).error = NaN(1,p.num_timesteps);
    % vars(i).error_aot = vars(i).error;
    % vars(i).im = [];
    % vars(i).stokes_number = [];
%% Inertia sensors St=1, c=40
    % i = i+1;
    % vars(i).observer_type = "Inertia";
    % vars(i).interpolation_type = "linear";
    % vars(i).sensors = initialSensorLocations;
    % vars(i).vel = zeros(1, num_sensors);
    % vars(i).rho = 13.9197;
    % vars(i).diameter = 10;
    % vars(i).marker = 'o';
    % vars(i).color = "k";
    % vars(i).off_grid = true;
    % vars(i).error = NaN(1,p.num_timesteps);
    % vars(i).error_aot = vars(i).error;
    % vars(i).im = [];
    % vars(i).amplitude = 40;
    % vars(i).stokes_number = [];
%% Target-Sensors
    i = i+1;
    vars(i).observer_type = "Target Sensors";
    vars(i).interpolation_type = "linear";
    vars(i).sensors = initialSensorLocations;
    vars(i).error = NaN(1,p.num_timesteps);
    vars(i).error_aot = vars(i).error;
    vars(i).off_grid = true;
    vars(i).K = K;
    vars(i).alg = 1;
    vars(i).sensor_speed = 1;
    vars(i).marker = 'o-';
    vars(i).color = 'green';
    vars(i).mapping = [];
    vars(i).target_sensors = vars(i).sensors;
    vars(i).im = {};
%% Target-Sensors
    i = i+1;
    vars(i).observer_type = "Target Sensors";
    vars(i).interpolation_type = "linear";
    vars(i).sensors = initialSensorLocations;
    vars(i).error = NaN(1,p.num_timesteps);
    vars(i).error_aot = vars(i).error;
    vars(i).off_grid = true;
    vars(i).K = K;
    vars(i).alg = 1;
    vars(i).sensor_speed = inf;
    vars(i).marker = 'o-';
    vars(i).color = 'green';
    vars(i).mapping = [];
    vars(i).target_sensors = vars(i).sensors;
    vars(i).im = {};
%% Target-Sensors
    % i = i+1;
    % vars(i).observer_type = "Target Sensors";
    % vars(i).interpolation_type = "linear";
    % vars(i).num_sensors = num_sensors;
    % vars(i).sensors = linspace(p.x(1), p.x(end), num_sensors);
    % vars(i).error = NaN(1,p.num_timesteps);
    % vars(i).error_aot = vars(i).error;
    % vars(i).off_grid = true;
    % vars(i).K = K;
    % vars(i).alg = 2;
    % vars(i).sensor_speed = inf;
    % vars(i).marker = 'x-';
    % vars(i).color = 'red';
    % vars(i).mapping = [];
    % vars(i).target_sensors = [];
    % vars(i).im = {};
%% Forward-Sensors
%     i = i+1;
%     vars(i).observer_type = "Forward Sensors";
%     vars(i).interpolation_type = "linear";
%     vars(i).num_sensors = num_sensors;
%     vars(i).sensors = linspace(p.x(1), p.x(end), num_sensors);
%     vars(i).change_triggered = false;
%     vars(i).error = NaN(1,p.num_timesteps);
%     vars(i).error_aot = vars(i).error;
%     vars(i).off_grid = true;
%     vars(i).sensor_speed = 30;
%     vars(i).marker = 'o';
%     vars(i).color = 'green';
%     vars(i).im = {};
end
