function vars = DataAssimilationVariables_KSE(p)
% Author: Collin Victor. Last modified on 2020-09-25.
% Adapted for use by NSE 2D DA programs
% Initializes information for various types of observer regimes
% Including: Movement types of observers (i.e. mobile and static), type of
% interpolation, time type of observers (i.e. Chi vs Delta), and observer reset
% functionality.
vars = repelem(struct,1,1);
i = 0;
num_sensors = 1024;
% right_half = 10;
% left_half = num_sensors - right_half;
initialSensorLocations = linspace(p.x(1), p.x(end), num_sensors);

% Uncomment the type of observer you want to use.
%% Uniform sensors
    % i = i+1;
    % vars(i).observer_type = "Uniform";
    % vars(i).interpolation_type = "linear";
    % vars(i).sensors = linspace(p.x(1), p.x(end), num_sensors);
    % vars(i).off_grid = true;
    % vars(i).error = NaN(1,p.num_timesteps);
    % vars(i).error_aot = vars(i).error;
    % vars(i).marker = 's';
    % vars(i).color = 'blue';
    % vars(i).im = [];
%% Lagrangian
    % i = i+1;
    % vars(i).observer_type = "Lagrangian";
    % vars(i).interpolation_type = "linear";
    % vars(i).sensors = initialSensorLocations;
    % vars(i).marker = 's';
    % vars(i).diameter = 0;
    % vars(i).rho = 0;
    % vars(i).color = [0.502, 0, 0.408];
    % vars(i).outline_color = [0.502, 0, 0.408];
    % vars(i).off_grid = true;
    % vars(i).error = NaN(1,p.num_timesteps);
    % vars(i).error_aot = vars(i).error;
    % vars(i).amplitude = 0;
    % vars(i).stokes_number = [];
    % vars(i).sensor_history = zeros(p.T/p.dt+1, num_sensors);
    % vars(i).sensor_history(1, :) = vars(i).sensors;
%% Lagrangian-Creeps 40
    % i = i+1;
    % vars(i).observer_type = "Lagrangian";
    % vars(i).interpolation_type = "linear";
    % vars(i).sensors = initialSensorLocations;
    % vars(i).marker = '^';
    % vars(i).diameter = 0;
    % vars(i).rho = 0;
    % vars(i).color = [0.85,0.33,0.10];
    % vars(i).outline_color = 'blue';
    % vars(i).off_grid = true;
    % vars(i).error = NaN(1,p.num_timesteps);
    % vars(i).error_aot = vars(i).error;
    % vars(i).amplitude = 40;
    % vars(i).stokes_number = [];
    % vars(i).sensor_history = zeros(p.T/p.dt+1, num_sensors);
    % vars(i).sensor_history(1, :) = vars(i).sensors;
 %% Inertia sensors St=0.001
    i = i+1;
    vars(i).observer_type = "Inertia";
    vars(i).interpolation_type = "linear";
    vars(i).sensors = linspace(p.x(1), p.x(end), num_sensors);
    vars(i).vel = zeros(1, num_sensors);
    vars(i).rho = 0.0139197;
    vars(i).diameter = 10;
    vars(i).marker = 'o';
    vars(i).color = "cyan";
    vars(i).off_grid = true;
    vars(i).error = NaN(1,p.num_timesteps);
    vars(i).error_aot = vars(i).error;
    vars(i).amplitude = 0;
    vars(i).stokes_number = [];
 %% Inertia sensors St=0.01
    i = i+1;
    vars(i).observer_type = "Inertia";
    vars(i).interpolation_type = "linear";
    vars(i).sensors = initialSensorLocations;
    vars(i).vel = zeros(1, num_sensors);
    vars(i).rho = 0.139197;
    vars(i).diameter = 10;
    vars(i).marker = '^';
    vars(i).color = "red";
    vars(i).off_grid = true;
    vars(i).amplitude = 0;
    vars(i).error = NaN(1,p.num_timesteps);
    vars(i).error_aot = vars(i).error;
    vars(i).stokes_number = [];
 %% Inertia sensors St=0.1
    i = i+1;
    vars(i).observer_type = "Inertia";
    vars(i).interpolation_type = "linear";
    vars(i).sensors = initialSensorLocations;
    vars(i).vel = zeros(1, num_sensors);
    vars(i).rho = 1.39197;
    vars(i).diameter = 10;
    vars(i).marker = 'd';
    vars(i).color = "blue";
    vars(i).off_grid = true;
    vars(i).amplitude = 0;
    vars(i).error = NaN(1,p.num_timesteps);
    vars(i).error_aot = vars(i).error;
    vars(i).stokes_number = [];
%%  Inertia sensors St=1
    i = i+1;
    vars(i).observer_type = "Inertia";
    vars(i).interpolation_type = "linear";
    vars(i).sensors = initialSensorLocations;
    vars(i).vel = zeros(1, num_sensors);
    vars(i).rho = 13.9197;
    vars(i).diameter = 10;
    vars(i).marker = 'p';
    vars(i).color = "magenta";
    vars(i).off_grid = true;
    vars(i).error = NaN(1,p.num_timesteps);
    vars(i).error_aot = vars(i).error;
    vars(i).amplitude = 0;
    vars(i).stokes_number = [];
    vars(i).sensor_history = zeros(p.T/p.dt+1, num_sensors);
    vars(i).sensor_history(1, :) = vars(i).sensors;
%% Inertia sensors St=1, c=40
    % i = i+1;
    % vars(i).observer_type = "Inertia";
    % vars(i).interpolation_type = "linear";
    % vars(i).sensors = initialSensorLocations;
    % vars(i).vel = zeros(1, num_sensors);
    % vars(i).rho = 13.9197;
    % vars(i).diameter = 10;
    % vars(i).marker = 'o';
    % vars(i).color = "k";
    % vars(i).off_grid = true;
    % vars(i).error = NaN(1,p.num_timesteps);
    % vars(i).error_aot = vars(i).error;
    % vars(i).amplitude = 40;
    % vars(i).stokes_number = [];
%% Target-Sensors
    % i = i+1;
    % vars(i).observer_type = "Directed";
    % vars(i).interpolation_type = "linear";
    % vars(i).sensors = initialSensorLocations;
    % vars(i).error = NaN(1,p.num_timesteps);
    % vars(i).error_aot = vars(i).error;
    % vars(i).off_grid = true;
    % vars(i).K = 0;
    % vars(i).alg = 1;
    % vars(i).sensor_speed = inf;
    % vars(i).marker = 'o';
    % vars(i).color = [1.00,0.77,0.23];
    % vars(i).outline_color = "blue";
    % vars(i).mapping = [];
    % vars(i).target_sensors = vars(i).sensors;
    % vars(i).average_speed = zeros(num_sensors, p.num_timesteps);
    % vars(i).sensor_history = zeros(p.T/p.dt+1, num_sensors);
    % vars(i).sensor_history(1, :) = vars(i).sensors;
%% Forward-Sensors
    % i = i+1;
    % vars(i).observer_type = "Forward Sensors";
    % vars(i).interpolation_type = "linear";
    % vars(i).num_sensors = num_sensors;
    % vars(i).sensors = linspace(p.x(1), p.x(end), num_sensors);
    % vars(i).change_triggered = false;
    % vars(i).error = NaN(1,p.num_timesteps);
    % vars(i).error_aot = vars(i).error;
    % vars(i).off_grid = true;
    % vars(i).sensor_speed = 30;
    % vars(i).marker = 'o';
    % vars(i).color = 'green';
%% Spaced Biased-Sensors
    % i = i+1;
    % vars(i).observer_type = "Bias Sensors";
    % vars(i).interpolation_type = "linear";
    % vars(i).num_sensors = num_sensors;
    % vars(i).sensors = [linspace(0, floor(p.Lx/2), left_half) linspace(ceil(p.Lx/2), p.Lx-p.dx, right_half)];
    % % disp(vars(i).sensors)
    % vars(i).error = NaN(1,p.num_timesteps);
    % vars(i).error_aot = vars(i).error;
    % vars(i).off_grid = true;
    % vars(i).marker = 's';
    % vars(i).outline_color = 'k';
    % vars(i).color = 'y';
end
